#!/bin/sh

ENABLED=yes
PROCS=msmtpd
ARGS=""
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Hacky way of starting non-daemon binary
PRECMD="$PREARGS daemonize -p /opt/var/run/msmtpd.pid /opt/sbin/msmtpd $ARGS"
PREARGS="echo"

. /opt/etc/init.d/rc.func
