#!/bin/sh

ENABLED=yes
PROCS=http-to-https-proxy
ARGS="8888 443 4096"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Hacky way of starting non-daemon binary
PRECMD="$PREARGS daemonize -p /opt/var/run/http-to-https-proxy.pid /opt/bin/http-to-https-proxy $ARGS"
PREARGS="echo"

. /opt/etc/init.d/rc.func
