#!/bin/sh

ENABLED=yes
PROCS=http-to-https-proxy
ARGS="8888 443 4096 2>&1 > /dev/null &"
PREARGS="nohup"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
