name: Build

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages to build (override)'
        required: false
        default: ''

env:
  PACKAGES: xupnpd2-jacklul http-to-https-proxy http-to-https-proxy_nohf msmtpd

jobs:
  build:
    concurrency: build-${{ github.ref_name || github.run_id }}-${{ matrix.arch }}
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.allow-failure }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64-3.10
            dir: aarch64-k3.10
            allow-failure: false
          - arch: armv7-3.2
            dir: armv7sf-k3.2
            allow-failure: false
          #- arch: mipsel-3.4
          #  dir: mipselsf-k3.4
          #  allow-failure: true
          #- arch: mips-3.4
          #  dir: mipssf-k3.4
          #  allow-failure: true
          - arch: x64-3.2
            dir: x64-k3.2
            allow-failure: false

    steps:
    - uses: actions/checkout@v6
      with:
        repository: Entware/Entware

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential flex gawk gcc-multilib gettext git libncurses5-dev libssl-dev python2 python-is-python3 python3-distutils subversion unzip zlib1g-dev rsync

    - name: Activate platform configuration
      run: ln -s configs/${{ matrix.arch }}.config .config

    - name: Get commit hash for cache key
      id: hash
      run: echo "RESULT=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - uses: actions/cache/restore@v5
      continue-on-error: true
      id: restore-cache
      with:
        path: |
          bin
          build_dir
          staging_dir
        key: ${{ matrix.arch }}-${{ steps.hash.outputs.RESULT }}

    - name: Build tools and toolchain
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        make tools/install -j$(nproc) ${{ vars.TOOLCHAIN_EXTRA_COMPILE_ARGUMENTS || '' }}
        make toolchain/install -j$(nproc) ${{ vars.TOOLCHAIN_EXTRA_COMPILE_ARGUMENTS || '' }}
        make target/compile -j$(nproc) ${{ vars.TOOLCHAIN_EXTRA_COMPILE_ARGUMENTS || '' }}

    - uses: actions/cache/save@v5
      continue-on-error: true
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        path: |
          bin
          build_dir
          staging_dir
        key: ${{ matrix.arch }}-${{ steps.hash.outputs.RESULT }}

    - name: Fetch feeds (${{ github.ref_name }})
      run: |
        echo "src-git jacklul https://github.com/jacklul/entware-packages.git;${{ github.ref_name }}" >> feeds.conf
        make package/symlinks

    - name: Build packages
      if: env.PACKAGES != '' || github.event.inputs.packages != ''
      continue-on-error: ${{ matrix.allow-failure }}
      run: |
        for PACKAGE in ${{ github.event.inputs.packages || env.PACKAGES }}; do
          echo "CONFIG_PACKAGE_${PACKAGE}=m" >> .config
        done

        for PACKAGE in ${{ github.event.inputs.packages || env.PACKAGES }}; do
          export BUILD_VARIANT=

          if [[ "$PACKAGE" == *_nohf ]]; then
            if [ "${{ matrix.arch == 'armv7-2.6' || matrix.arch == 'armv7-3.2' }}" = "true" ]; then
              export BUILD_VARIANT=nohf
              PACKAGE="${PACKAGE%_nohf}"
            else
              continue
            fi
          fi

          make package/$PACKAGE/compile -j$(nproc) ${{ vars.PACKAGES_EXTRA_COMPILE_ARGUMENTS || '' }} ${{ matrix.allow-failure && '|| true' || '' }} ; 
        done

    - name: Copy packages to artifacts directory
      run: |
        mkdir -v artifacts
        for PACKAGE in ${{ github.event.inputs.packages || env.PACKAGES }}; do cp -nv bin/targets/*/*/packages/$PACKAGE*.ipk artifacts || true; done

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.dir }}
        path: artifacts/*

  upload:
    concurrency: upload-${{ github.ref_name || github.run_id }}
    needs: build
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        continue-on-error: true
        with:
          ref: gh-pages

      - uses: actions/checkout@v6
        with:
          repository: Entware/ipk-html-indexer
          path: ipk-html-indexer

      - run: mv ipk-html-indexer ../ipk-html-indexer

      - name: Remove existing content
        run: find . -mindepth 1 -maxdepth 1 \( ! -name ".git" -type d -exec rm -fr "{}" \; \) -o \( -type f -exec rm -f "{}" \; \)

      - uses: actions/download-artifact@v4

      - name: Run ipk-html-indexer
        run: |
          sudo ln -sv "$GITHUB_WORKSPACE/../ipk-html-indexer/mkindex.py" /usr/local/bin/mkindex.py
          sudo ln -sv "$GITHUB_WORKSPACE/../ipk-html-indexer/mkhtml.py" /usr/local/bin/mkhtml.py

          for dir in ${{ github.workspace }}/*/; do
            if [ -d "$dir" ] && ls "$dir"/*.ipk > /dev/null 2>&1; then
              bash ../ipk-html-indexer/index_feed.sh -h -f "$dir"
              sed 's#href="/css#href="../css#' -i "$dir/Packages.html"
            fi
          done

          cp -rfv ../ipk-html-indexer/css .

      - run: mv .git ../.git.bak; mv css ../css.bak

      - uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: .

      - run: find . -type f -name index.html -exec sudo chown $(id -u):$(id -g) {} \;

      - run: mv ../.git.bak .git; mv ../css.bak css

      - run: ls -al . *

      - run: git branch -m gh-pages gh-pages.old
        continue-on-error: true

      - uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref_name == 'master' && github.event.inputs.packages == '' }}
        with:
          branch: gh-pages
          folder: .
          commit-message: Upload
          single-commit: true
          force: true
          git-config-name: 'github-actions[bot]'
          git-config-email: '41898282+github-actions[bot]@users.noreply.github.com'

      - run: rm -fr .git
        if: ${{ github.ref_name != 'master' || github.event.inputs.packages != '' }}

      - uses: actions/upload-artifact@v7
        if: ${{ github.ref_name != 'master' || github.event.inputs.packages != '' }}
        with:
          name: upload
          path: .
